server:
  port: 8090

spring:
  datasource:
    name:
    url: jdbc:mysql://127.0.0.1:3306/l1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: '@si13044'

mybatis:
  mapper-locations: classpath:mapper/*.xml